
on: [push]

jobs:
  build_python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
  depchecktest:
    needs: build_python
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies && safety
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety
      - name: Depcheck
        run: |
          safety check -r requirements.txt --output depcheck.json
        continue-on-error: true
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: depcheck.json
  slscan: 
    runs-on: ubuntu-latest
    needs: depchecktest
    name: Perform SL Scan
    steps: 
    - uses: actions/checkout@v4 
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - uses: ShiftLeftSecurity/scan-action@master
      with:
        type: "credscan,python,depscan"
    - uses: actions/upload-artifact@master
      with:
        name: SLSCAN reports
        path: ${{github.workspace}}/reports

  build_and_push:
    name: Build & Push to DockerHub
    needs: slscan
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cguanwei/python_cybersercurity

